name: dotenv2dart_example
version: 0.0.1
author: Amadeu Cavalcante <amadeu01@gmail.com>

environment:
  sdk: '>=2.3.0 <3.0.0'

dependencies:
  dotenv2dart:
    path: ../dotenv_to_dart/

dev_dependencies:
  build_runner: ^1.5.0
