name: dotenv2dart
description: A dart generator for .env files.
version: 0.0.1
homepage: https://github.com/amadeu01/dotenv2dart
author: Amadeu Cavalcante <amadeu01@gmail.com>

environment:
  sdk: '>=2.3.0 <3.0.0'

dependencies:
  path: ^1.6.0
  meta: ^1.1.6
  build: ^1.1.4
  build_config: ^0.4.0
  dart_style: ^1.2.8
  recase: ^2.0.1

dev_dependencies:
  pedantic: ^1.7.0
  test: ^1.6.0
